### ISSUE TITLE
Nullpointer on BankAccountSerializer when adding new IBAN Bankaccount

### ISSUE THREAD

**Issue by felixhagspiel** [Mangopay/mangopay2-java-sdk#162]
I am getting a Nullpointer Exception when creating a new IBAN bankaccount in V2.8.1. Might be related to this Issue from last year: https://github.com/Mangopay/mangopay2-java-sdk/issues/126

```
12:28:35,708 ERROR [stderr] (default task-7) java.lang.NullPointerException
12:28:35,709 ERROR [stderr] (default task-7) 	at com.mangopay.core.serializer.BankAccountSerializer.serialize(BankAccountSerializer.java:25)
12:28:35,709 ERROR [stderr] (default task-7) 	at com.mangopay.core.serializer.BankAccountSerializer.serialize(BankAccountSerializer.java:13)
12:28:35,709 ERROR [stderr] (default task-7) 	at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70)
12:28:35,709 ERROR [stderr] (default task-7) 	at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:63)
12:28:35,709 ERROR [stderr] (default task-7) 	at com.google.gson.Gson.toJson(Gson.java:593)
12:28:35,710 ERROR [stderr] (default task-7) 	at com.google.gson.Gson.toJson(Gson.java:572)
12:28:35,710 ERROR [stderr] (default task-7) 	at com.google.gson.Gson.toJson(Gson.java:527)
12:28:35,710 ERROR [stderr] (default task-7) 	at com.google.gson.Gson.toJson(Gson.java:507)
12:28:35,710 ERROR [stderr] (default task-7) 	at com.mangopay.core.RestTool.doRequest(RestTool.java:367)
12:28:35,710 ERROR [stderr] (default task-7) 	at com.mangopay.core.RestTool.request(RestTool.java:144)
12:28:35,710 ERROR [stderr] (default task-7) 	at com.mangopay.core.APIs.ApiBase.createObject(ApiBase.java:253)
12:28:35,711 ERROR [stderr] (default task-7) 	at com.mangopay.core.APIs.ApiBase.createObject(ApiBase.java:272)
12:28:35,711 ERROR [stderr] (default task-7) 	at com.mangopay.core.APIs.implementation.UserApiImpl.createBankAccount(UserApiImpl.java:110)
12:28:35,711 ERROR [stderr] (default task-7) 	at com.mangopay.core.APIs.implementation.UserApiImpl.createBankAccount(UserApiImpl.java:104)
```

**Comment by felixhagspiel** [comment]
It seems that in Version 2.8.1 we now have to explicitly set the bankaccount-type inside the `BankAccount`-Object (i.e. `newPaymentBankaccount.setType(BankAccountType.IBAN);`), which was not neccessary in earlier releases. 
Where are SDK changes like this documented? I did not find this in the release notes.
Closing this issue now as it is fixed for me.
