### ISSUE TITLE
IOException when trying to create a document page

### ISSUE THREAD

**Issue by rcharlier-delipay** [Mangopay/mangopay2-java-sdk#176]
Good evening,

My team is integrating the Mangopay SDK, everything works well but an error occurred when using the createKycPage(String userId, String kycDocumentId, byte[] binaryData) : 
`java.io.IOException: Error writing to server`

After getting the responseBody from the sdk debug mode and trying to call the API from Postman, the document is added with a 204 success code.

Do you have any idea why that exception occured ?

Thank you in advance.

**Comment by rcharlier-delipay** [comment]
Could you please give me some support about that @catacraciun (@mickaelpois @Riwak etc.)

**Comment by rcharlier-delipay** [comment]
@catacraciun any help please... ?

**Comment by vlad-mircan** [comment]
Could you please provide some more details? I tested the scenario you are talking about and it seems to be working fine on my end ( OK response from server, no exception thrown by any of the `createKycPage` calls including the one with `binaryData `as parameter).

**Comment by rcharlier-delipay** [comment]
@vlad-mircan, when submitting the KYC document page, we get that stacktrace.

All other call are ok. Thank you for your help

`java.io.IOException: Error writing to server
	at java.base/sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:718) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:730) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1608) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515) ~[na:na]
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:335) ~[na:na]
	at com.mangopay.core.RestTool.doRequest(RestTool.java:390) ~[mangopay2-java-sdk-2.10.1.jar:na]
	at com.mangopay.core.RestTool.request(RestTool.java:144) ~[mangopay2-java-sdk-2.10.1.jar:na]
	at com.mangopay.core.APIs.ApiBase.createObject(ApiBase.java:256) ~[mangopay2-java-sdk-2.10.1.jar:na]
	at com.mangopay.core.APIs.implementation.UserApiImpl.createKycPage(UserApiImpl.java:176) ~[mangopay2-java-sdk-2.10.1.jar:na]
	at com.mangopay.core.APIs.implementation.UserApiImpl.createKycPage(UserApiImpl.java:165) ~[mangopay2-java-sdk-2.10.1.jar:na]
	at fr.delipay.backend.service.MangopayService.createKycDocumentPage(MangopayService.java:213) ~[classes/:na]
`

**Comment by SoloJr** [comment]
@rcharlier-delipay Hello. I'm Mircea and I'm handling some of the mangopay issues. As far as I've seen this error also occurs on the .net sdk, so I'm guessing the problem is in the MangoPaySDK. If I run the tests one by one, the CreateKycPage runs successfully. If there are multiple calls in a short time, some return the error message, but they get created.

`{"Message":"Internal Server Error","Type":"other","Id":"174e90cf-75fe-42ee-bd29-ccb915bb0ec0#1587021434","Date":1587021436.0,"errors":null}`

**Comment by fmaziere** [comment]
Hello, I got the same error as rcharlier-delipay.  
`java.io.IOException: Error writing to server at`

And it's work well from Postman with the API.
I have tested with different kind of files

**Comment by rcharlier-delipay** [comment]
@catacraciun some other users seem to have same issues. That problem evolved by our side. One by one all my developers have the same issues than @SoloJr (first call is ok, second call failed). Could you please give us any information about that issue which is production breaking for us. Thank you in advance.

**Comment by rcharlier-delipay** [comment]
For me the problem have been solved without any change (and no sdk upgrade nether).

**Comment by mangomaxoasis** [comment]
Great @rcharlier-delipay 
The change was impacted at the API level
