### ISSUE TITLE
java.lang.UnsupportedOperationException: JsonNull In PayInDeserializer

### ISSUE THREAD

**Issue by ptroc** [Mangopay/mangopay2-java-sdk#203]
Hi, I have issue with getting PayIN details for event
after fetching details of payin i get exception and stack trace: 
```Caused by: java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsString(JsonElement.java:179) ~[gson-2.8.6.jar:na]
	at com.mangopay.core.deserializer.PayInDeserializer.deserialize(PayInDeserializer.java:145) ~[mangopay2-java-sdk-2.11.0.jar:na]
	at com.mangopay.core.deserializer.PayInDeserializer.deserialize(PayInDeserializer.java:19) ~[mangopay2-java-sdk-2.11.0.jar:na]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.6.jar:na]
	at com.mangopay.core.RestTool.castResponseToEntity(RestTool.java:518) ~[mangopay2-java-sdk-2.11.0.jar:na]
	at com.mangopay.core.RestTool.doRequest(RestTool.java:420) ~[mangopay2-java-sdk-2.11.0.jar:na]
	at com.mangopay.core.RestTool.request(RestTool.java:144) ~[mangopay2-java-sdk-2.11.0.jar:na]
	at com.mangopay.core.RestTool.request(RestTool.java:168) ~[mangopay2-java-sdk-2.11.0.jar:na]
	at com.mangopay.core.APIs.ApiBase.getObject(ApiBase.java:306) ~[mangopay2-java-sdk-2.11.0.jar:na]
	at com.mangopay.core.APIs.implementation.PayInApiImpl.get(PayInApiImpl.java:46) ~[mangopay2-java-sdk-2.11.0.jar:na]
```

problem is in com.mangopay.core.deserializer.PayInDeserializer#deserialize 
in branch `EXTERNAL_INSTRUCTION` as the code below is not validating null values, and WireReference filed in response is null 

```case EXTERNAL_INSTRUCTION:
                JsonObject debitedBankAccount = object.get("DebitedBankAccount").getAsJsonObject();
                PayInExecutionDetailsBankingAlias payInExecutionDetailsBankingAlias = new PayInExecutionDetailsBankingAlias(
                        object.get("BankingAliasId").getAsString(), 
                        object.get("WireReference").getAsString(),
                        (DebitedBankAccount) context.deserialize(debitedBankAccount, DebitedBankAccount.class)
                );
                payIn.setExecutionDetails(payInExecutionDetailsBankingAlias);
                break;
```

redacted json response: 

```{
    "CreditedUserId": "00000001",
    "AuthorId": "00000001",
    "CreditedWalletId": "00002",
    "DebitedBankAccount": {
        "IBAN": "DE000VALID_IBAN",
        "BIC": "VALID_BIC",
        "AccountNumber": null,
        "Country": null,
        "OwnerName": "Company GmbH",
        "Type": "IBAN"
    },
    "BankingAliasId": "0101010101",
    "Type": "PAYIN",
    "Status": "SUCCEEDED",
    "ResultCode": "000000",
    "ResultMessage": "Success",
    "Nature": "REGULAR",
    "CreationDate": 159661262,
    "ExecutionDate": 159661262,
    "WireReference": null,
    "PaymentType": "BANK_WIRE",
    "ExecutionType": "EXTERNAL_INSTRUCTION",
    "DebitedWalletId": null,
    "Fees": {
        "Currency": "EUR",
        "Amount": 0
    },
    "DebitedFunds": {
        "Currency": "EUR",
        "Amount": 1010
    },
    "CreditedFunds": {
        "Currency": "EUR",
        "Amount": 1010
    },
    "Id": "00000077789",
    "Tag": null
}
```

**Comment by ptroc** [comment]
Here is patch for this issue: https://gist.github.com/ptroc/9000bbe4bc45f7a400ac06eebc3f4f21

**Comment by mangomaxoasis** [comment]
Thank you so much @ptroc 
We're reviewing the patch, we'll release as soon as possible
