### ISSUE TITLE
DisputeReasonType LATE_FAILURE_CONTACT_USER missing in enum

### ISSUE THREAD

**Issue by csandras** [Mangopay/mangopay2-java-sdk#67]
Today we received a new dispute created event. 

If we want to get more info about it (mangoApi.Disputes.get(id)) the following exception is thrown: 

java.lang.IllegalArgumentException: No enum constant com.mangopay.core.enumerations.DisputeReasonType.LATE_FAILURE_CONTACT_USER
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.mangopay.core.RestTool.castResponseToEntity(RestTool.java:739)
        at com.mangopay.core.RestTool.castResponseToEntity(RestTool.java:554)
        at com.mangopay.core.RestTool.castResponseToEntity(RestTool.java:666)
        at com.mangopay.core.RestTool.castResponseToEntity(RestTool.java:554)
        at com.mangopay.core.RestTool.doRequest(RestTool.java:421)
        at com.mangopay.core.RestTool.request(RestTool.java:142)
        at com.mangopay.core.RestTool.request(RestTool.java:166)
        at com.mangopay.core.APIs.ApiBase.getObject(ApiBase.java:261)
        at com.mangopay.core.APIs.ApiBase.getObject(ApiBase.java:276)
        at com.mangopay.core.APIs.ApiDisputes.get(ApiDisputes.java:38)

LATE_FAILURE_CONTACT_USER is missing in DisputeReasonType.

**Comment by hobailey** [comment]
Thanks @csandras for bringing this up :-)
